; Generated by Ripple C99 Compiler (rcc)

; Function: putchar
putchar:
; === Processing instruction #0: InlineAsm { assembly: "STORE RV0, R0, R0" } ===
    STORE RV0, R0, R0
; === Processing instruction #1: Return(None) ===
    RET
