; Generated by Ripple C99 Compiler (rcc)

_init_globals:
    RET
; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
    LI R3, 82
    CALL putchar
    LI R3, 84
    CALL putchar
    LI R3, 10
    CALL putchar
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
