; Generated by Ripple C99 Compiler (rcc)

_init_globals:
    RET
main:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 12 slots for locals
    ADDI SP, SP, 12
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
    ADD S3, FP, R0
    ADD S2, FP, R0
    ADDI S2, S2, 2
    ADD S1, S3, R0
; GEP: Setting bank info for t2 to Stack
    LI S0, 10
    STORE S0, SB, S1
; Recompute alloca t0 at FP+0
    ADD T7, FP, R0
    ADDI T6, T7, 1
; GEP: Setting bank info for t3 to Stack
    LI T5, 20
    STORE T5, SB, T6
    ADD T4, S2, R0
; GEP: Setting bank info for t4 to Stack
; Recompute alloca t0 at FP+0
    ADD T3, FP, R0
    ADD T2, T3, R0
; GEP: Setting bank info for t5 to Stack
    ADD T1, T4, R0
; GEP: Setting bank info for t6 to Stack
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T0, SB, T2
    STORE T0, SB, T1
; Recompute alloca t0 at FP+0
    ADD S3, FP, R0
    ADDI S0, S3, 1
; GEP: Setting bank info for t8 to Stack
    ADDI T5, T7, 1
; GEP: Setting bank info for t9 to Stack
; Load instruction: t10 = load FatPtr(FatPointer { addr: Temp(8), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(8), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op3_t10 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S2, SB, S0
    STORE S2, SB, T5
; Recompute alloca t1 at FP+2
    ADD T3, FP, R0
    ADDI T3, T3, 2
    ADD T4, T3, R0
; GEP: Setting bank info for t11 to Stack
    ADDI S3, T4, 1
; GEP: Setting bank info for t12 to Stack
; Load instruction: t13 = load FatPtr(FatPointer { addr: Temp(12), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(12), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op4_t13 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T7, SB, S3
    LI T3, 20
    XOR T4, T7, T3
; Spill t2 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE S1, SB, SC
    LI S1, 1
    SLTU T7, T4, S1
    BEQ T7, R0, L_main_2
; Branch to L_main_2 if condition is false
    BEQ R0, R0, L_main_1
; Unconditional branch to L_main_1 (condition was true)
L_main_1:
    LI T4, 89
; Spill live registers before call
; Spill t3 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T6, SB, SC
; Spill t5 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE T2, SB, SC
; Spill t7 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 15
    STORE T0, SB, SC
; Spill t6 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE T1, SB, SC
; Spill t8 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE S0, SB, SC
; Spill t10 to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 18
    STORE S2, SB, SC
; Spill t9 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 19
    STORE T5, SB, SC
; Spill t12 to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 20
    STORE S3, SB, SC
; Spill const_f0_op7_89 to slot 9
    ADD SC, FP, R0
    ADDI SC, SC, 21
    STORE T4, SB, SC
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T4, R0
; Call function putchar
    CALL putchar
    BEQ R0, R0, L_main_3
; Unconditional branch to L_main_3
L_main_2:
    LI S1, 78
; Spill live registers before call
; Spill const_f0_op8_78 to slot 10
    ADD SC, FP, R0
    ADDI SC, SC, 22
    STORE S1, SB, SC
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function putchar
    CALL putchar
    BEQ R0, R0, L_main_3
; Unconditional branch to L_main_3
L_main_3:
    LI T3, 10
; Spill live registers before call
; Spill const_f0_op9_10 to slot 11
    ADD SC, FP, R0
    ADDI SC, SC, 23
    STORE T3, SB, SC
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T3, R0
; Call function putchar
    CALL putchar
    LI RV0, 0
; Jump to epilogue
    BEQ R0, R0, L_main_99999
L_main_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
