; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: add
add:
    ADD R5, R3, R4
    ADD R3, R5, R0
    RET
; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
L1:
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R3, 5
    ADDI R6, R15, 1
; Store 5 to [t0]
    STORE R3, R13, R6
; Alloca for t1 at FP+2
    ADDI R5, R15, 2
    LI R3, 10
    ADDI R6, R15, 2
; Store 10 to [t1]
    STORE R3, R13, R6
; Alloca for t2 at FP+3
    ADDI R5, R15, 3
; Load from [t0] to t3
    ADDI R7, R15, 1
    LOAD R6, R13, R7
; Load from [t1] to t4
    ADDI R9, R15, 2
    LOAD R8, R13, R9
    ADD R3, R6, R0
    ADD R4, R8, R0
    CALL add
    ADD R10, R3, R0
    ADDI R5, R15, 3
; Store t5 to [t2]
    STORE R10, R13, R5
; Load from [t2] to t6
    ADDI R6, R15, 3
    LOAD R5, R13, R6
    LI R4, 15
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L2
    BEQ R0, R0, L3
L2:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L4
L3:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L4
L4:
    LI R3, 10
    STORE R3, R0, R0
; Load from [t2] to t8
    ADDI R6, R15, 3
    LOAD R5, R13, R6
    ADD R3, R5, R0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
