; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
; Alloca for t0 at FP+1
    ADDI R3, R15, 1
    LI R4, 10
    ADDI R5, R15, 1
; Store 10 to [t0]
    STORE R4, R13, R5
    ADDI R6, R15, 1
    LI R7, 1
    ADD R8, R6, R7
    LI R3, 20
; Store 20 to [t1]
    STORE R3, R0, R8
; Alloca for t2 at FP+3
    ADDI R4, R15, 3
    ADDI R6, R15, 1
; Load from [t0] to t3
    LOAD R5, R13, R6
    ADDI R7, R15, 1
    LI R8, 1
    ADD R3, R7, R8
; Load from [t4] to t5
    LOAD R4, R0, R3
    ADD R5, R5, R4
    ADDI R6, R15, 3
; Store t6 to [t2]
    STORE R5, R13, R6
    ADDI R8, R15, 3
; Load from [t2] to t7
    LOAD R7, R13, R8
    ADD R3, R7, R0
    RET
