; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    LI R3, 1
    LI R4, 1
    SLT R9, R3, R4
    SLT R10, R4, R3
    OR R5, R9, R10
    LI R9, 1
    SUB R5, R9, R5
    BNE R5, R0, L1
    BEQ R0, R0, L2
L1:
    LI R6, 89
    STORE R6, R0, R0
    BEQ R0, R0, L3
L2:
    LI R7, 78
    STORE R7, R0, R0
    BEQ R0, R0, L3
L3:
    LI R8, 2
    LI R3, 2
    SLT R9, R8, R3
    SLT R10, R3, R8
    OR R4, R9, R10
    LI R9, 1
    SUB R4, R9, R4
    BNE R4, R0, L4
    BEQ R0, R0, L5
L4:
    LI R5, 89
    STORE R5, R0, R0
    BEQ R0, R0, L6
L5:
    LI R6, 78
    STORE R6, R0, R0
    BEQ R0, R0, L6
L6:
    LI R7, 4
    LI R8, 4
    SLT R9, R7, R8
    SLT R10, R8, R7
    OR R3, R9, R10
    LI R9, 1
    SUB R3, R9, R3
    BNE R3, R0, L7
    BEQ R0, R0, L8
L7:
    LI R4, 89
    STORE R4, R0, R0
    BEQ R0, R0, L9
L8:
    LI R5, 78
    STORE R5, R0, R0
    BEQ R0, R0, L9
L9:
    LI R6, 2
    LI R7, 2
    SLT R9, R6, R7
    SLT R10, R7, R6
    OR R8, R9, R10
    LI R9, 1
    SUB R8, R9, R8
    BNE R8, R0, L10
    BEQ R0, R0, L11
L10:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L12
L11:
    LI R4, 78
    STORE R4, R0, R0
    BEQ R0, R0, L12
L12:
; Alloca for t4 at FP+1
    ADDI R5, R15, 1
; Alloca for t5 at FP+11
    ADDI R6, R15, 11
; Alloca for t6 at FP+16
    ADDI R7, R15, 16
    LI R8, 10
    LI R3, 10
    SLT R9, R8, R3
    SLT R10, R3, R8
    OR R4, R9, R10
    LI R9, 1
    SUB R4, R9, R4
    BNE R4, R0, L13
    BEQ R0, R0, L14
L13:
    LI R5, 89
    STORE R5, R0, R0
    BEQ R0, R0, L15
L14:
    LI R6, 78
    STORE R6, R0, R0
    BEQ R0, R0, L15
L15:
    LI R7, 10
    LI R8, 10
    SLT R9, R7, R8
    SLT R10, R8, R7
    OR R3, R9, R10
    LI R9, 1
    SUB R3, R9, R3
    BNE R3, R0, L16
    BEQ R0, R0, L17
L16:
    LI R4, 89
    STORE R4, R0, R0
    BEQ R0, R0, L18
L17:
    LI R5, 78
    STORE R5, R0, R0
    BEQ R0, R0, L18
L18:
    LI R6, 12
    LI R7, 12
    SLT R9, R6, R7
    SLT R10, R7, R6
    OR R8, R9, R10
    LI R9, 1
    SUB R8, R9, R8
    BNE R8, R0, L19
    BEQ R0, R0, L20
L19:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L21
L20:
    LI R4, 78
    STORE R4, R0, R0
    BEQ R0, R0, L21
L21:
; Alloca for t10 at FP+22
    ADDI R5, R15, 22
    LI R6, 0
    ADDI R7, R15, 22
; Store 0 to [t10]
    STORE R6, R13, R7
    LI R8, 2
    LI R3, 2
    SLT R9, R8, R3
    SLT R10, R3, R8
    OR R4, R9, R10
    LI R9, 1
    SUB R4, R9, R4
    BNE R4, R0, L22
    BEQ R0, R0, L23
L22:
    LI R5, 89
    STORE R5, R0, R0
    BEQ R0, R0, L24
L23:
    LI R6, 78
    STORE R6, R0, R0
    BEQ R0, R0, L24
L24:
    ADDI R8, R15, 22
; Load from [t10] to t12
    LOAD R7, R13, R8
    LI R3, 0
    SLT R9, R7, R3
    SLT R10, R3, R7
    OR R4, R9, R10
    LI R9, 1
    SUB R4, R9, R4
    BNE R4, R0, L25
    BEQ R0, R0, L26
L25:
    LI R5, 89
    STORE R5, R0, R0
    BEQ R0, R0, L27
L26:
    LI R6, 78
    STORE R6, R0, R0
    BEQ R0, R0, L27
L27:
    LI R7, 10
    STORE R7, R0, R0
    LI R8, 0
    ADD R3, R8, R0
    RET
