; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
; Alloca for t0 at FP+1
    ADDI R3, R15, 1
    LI R4, 1
    ADDI R5, R15, 1
; Store 1 to [t0]
    STORE R4, R13, R5
; Alloca for t1 at FP+2
    ADDI R6, R15, 2
    LI R7, 2
    ADDI R8, R15, 2
; Store 2 to [t1]
    STORE R7, R13, R8
; Alloca for t2 at FP+3
    ADDI R3, R15, 3
    LI R4, 2
    ADDI R5, R15, 3
; Store 2 to [t2]
    STORE R4, R13, R5
; Alloca for t3 at FP+4
    ADDI R6, R15, 4
; Alloca for t4 at FP+9
    ADDI R7, R15, 9
    LI R8, 10
    ADDI R3, R15, 9
; Store 10 to [t4]
    STORE R8, R13, R3
    ADDI R5, R15, 1
; Load from [t0] to t5
    LOAD R4, R13, R5
    LI R6, 48
    ADD R7, R6, R4
    STORE R7, R0, R0
    LI R8, 32
    STORE R8, R0, R0
    ADDI R4, R15, 2
; Load from [t1] to t7
    LOAD R3, R13, R4
    LI R5, 48
    ADD R6, R5, R3
    STORE R6, R0, R0
    LI R7, 32
    STORE R7, R0, R0
    ADDI R3, R15, 3
; Load from [t2] to t9
    LOAD R8, R13, R3
    LI R4, 48
    ADD R5, R4, R8
    STORE R5, R0, R0
    LI R6, 32
    STORE R6, R0, R0
    ADDI R8, R15, 9
; Load from [t4] to t11
    LOAD R7, R13, R8
    LI R3, 48
    ADD R4, R3, R7
    STORE R4, R0, R0
    LI R5, 10
    STORE R5, R0, R0
    LI R6, 0
    ADD R3, R6, R0
    RET
