; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    LI R3, 65
    STORE R3, R0, R0
    LI R4, 66
    STORE R4, R0, R0
    LI R5, 10
    STORE R5, R0, R0
    LI R6, 0
    ADD R3, R6, R0
    RET
