; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    ; Initialize globals
    CALL _init_globals
    CALL main
    HALT

_init_globals:
; Global variable: global_counter at address 100
    LI R3, 5
    LI R4, 100
    STORE R3, R0, R4
; String literal OK! at address 101
    LI R3, 79
    LI R4, 101
    STORE R3, R0, R4
    LI R3, 75
    LI R4, 102
    STORE R3, R0, R4
    LI R3, 33
    LI R4, 103
    STORE R3, R0, R4
    LI R3, 0
    LI R4, 104
    STORE R3, R0, R4
    RET
; Function: main
main:
; Alloca for t0 at FP+1
    ADDI R3, R15, 1
    ADDI R4, R15, 1
    LI R5, 0
    ADD R6, R4, R5
    LI R7, 77
; Store 77 to [t1]
    STORE R7, R0, R6
    ADDI R8, R15, 1
    LI R3, 1
    ADD R4, R8, R3
    LI R5, 51
; Store 51 to [t2]
    STORE R5, R0, R4
    ADDI R6, R15, 1
    LI R7, 2
    ADD R8, R6, R7
    LI R3, 58
; Store 58 to [t3]
    STORE R3, R0, R8
    ADDI R4, R15, 1
    LI R5, 0
    ADD R6, R4, R5
; Load from [t4] to t5
    LOAD R7, R0, R6
    STORE R7, R0, R0
    ADDI R8, R15, 1
    LI R3, 1
    ADD R4, R8, R3
; Load from [t6] to t7
    LOAD R5, R0, R4
    STORE R5, R0, R0
    ADDI R6, R15, 1
    LI R7, 2
    ADD R8, R6, R7
; Load from [t8] to t9
    LOAD R3, R0, R8
    STORE R3, R0, R0
    LI R4, 32
    STORE R4, R0, R0
; Alloca for t10 at FP+4
    ADDI R5, R15, 4
    LI R6, 101
    ADDI R7, R15, 4
; Store @__str_0_4f4b21 to [t10]
    STORE R6, R13, R7
    ADDI R3, R15, 4
; Load from [t10] to t11
    LOAD R8, R13, R3
    LI R4, 0
    ADD R5, R8, R4
; Load from [t12] to t13
    LOAD R6, R0, R5
    STORE R6, R0, R0
    ADDI R8, R15, 4
; Load from [t10] to t14
    LOAD R7, R13, R8
    LI R3, 1
    ADD R4, R7, R3
; Load from [t15] to t16
    LOAD R5, R0, R4
    STORE R5, R0, R0
    ADDI R7, R15, 4
; Load from [t10] to t17
    LOAD R6, R13, R7
    LI R8, 2
    ADD R3, R6, R8
; Load from [t18] to t19
    LOAD R4, R0, R3
    STORE R4, R0, R0
    LI R5, 10
    STORE R5, R0, R0
; Alloca for t20 at FP+5
    ADDI R6, R15, 5
    LI R7, 65
    ADDI R8, R15, 5
; Store 65 to [t20]
    STORE R7, R13, R8
; Alloca for t21 at FP+6
    ADDI R3, R15, 6
    ADDI R4, R15, 5
    ADDI R5, R15, 6
; Store t20 to [t21]
    STORE R4, R13, R5
    ADDI R7, R15, 6
; Load from [t21] to t22
    LOAD R6, R13, R7
; Load from [t22] to t23
    LOAD R8, R0, R6
    STORE R8, R0, R0
; Alloca for t24 at FP+7
    ADDI R3, R15, 7
    ADDI R4, R15, 7
    LI R5, 0
    ADD R6, R4, R5
    LI R7, 66
; Store 66 to [t25]
    STORE R7, R0, R6
    ADDI R8, R15, 7
    LI R3, 1
    ADD R4, R8, R3
    LI R5, 67
; Store 67 to [t26]
    STORE R5, R0, R4
; Alloca for t27 at FP+9
    ADDI R6, R15, 9
    ADDI R7, R15, 7
    ADDI R8, R15, 9
; Store t24 to [t27]
    STORE R7, R13, R8
    ADDI R4, R15, 9
; Load from [t27] to t28
    LOAD R3, R13, R4
; Load from [t28] to t29
    LOAD R5, R0, R3
    STORE R5, R0, R0
    ADDI R7, R15, 9
; Load from [t27] to t30
    LOAD R6, R13, R7
    LI R8, 1
    ADD R3, R6, R8
; Load from [t31] to t32
    LOAD R4, R0, R3
    STORE R4, R0, R0
    LI R5, 10
    STORE R5, R0, R0
; Load from @global_counter to t33
    LI R9, 100
    LOAD R6, R0, R9
    LI R7, 5
    SLT R9, R6, R7
    SLT R10, R7, R6
    OR R8, R9, R10
    LI R9, 1
    SUB R8, R9, R8
    BNE R8, R0, L1
    BEQ R0, R0, L3
L1:
    LI R3, 71
    STORE R3, R0, R0
    LI R4, 111
    STORE R4, R0, R0
    LI R5, 111
    STORE R5, R0, R0
    LI R6, 100
    STORE R6, R0, R0
    LI R7, 33
    STORE R7, R0, R0
    LI R8, 10
    STORE R8, R0, R0
    BEQ R0, R0, L3
L3:
    LI R3, 0
    RET
