; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
    LI R3, 87
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R3, 0
    ADDI R6, R15, 1
; Store 0 to [t0]
    STORE R3, R13, R6
    BEQ R0, R0, L1
L1:
; Load from [t0] to t1
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R7, R5, R4
    BNE R7, R0, L2
    BEQ R0, R0, L3
L2:
; Load from [t0] to t3
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R3, 48
    ADD R7, R3, R5
    STORE R7, R0, R0
; Load from [t0] to t5
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 1
; Store t6 to [t0]
    STORE R7, R13, R8
    BEQ R0, R0, L1
L3:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 70
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t7 at FP+2
    ADDI R5, R15, 2
    LI R3, 0
    ADDI R6, R15, 2
; Store 0 to [t7]
    STORE R3, R13, R6
    BEQ R0, R0, L4
L4:
; Load from [t7] to t8
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R7, R5, R4
    BNE R7, R0, L5
    BEQ R0, R0, L7
L5:
; Load from [t7] to t10
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R3, 65
    ADD R7, R3, R5
    STORE R7, R0, R0
    BEQ R0, R0, L6
L6:
; Load from [t7] to t12
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 2
; Store t13 to [t7]
    STORE R7, R13, R8
    BEQ R0, R0, L4
L7:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 68
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t14 at FP+3
    ADDI R5, R15, 3
    LI R3, 0
    ADDI R6, R15, 3
; Store 0 to [t14]
    STORE R3, R13, R6
    BEQ R0, R0, L8
L8:
; Load from [t14] to t15
    ADDI R6, R15, 3
    LOAD R5, R13, R6
    LI R3, 88
    ADD R7, R3, R5
    STORE R7, R0, R0
; Load from [t14] to t17
    ADDI R6, R15, 3
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 3
; Store t18 to [t14]
    STORE R7, R13, R8
    BEQ R0, R0, L9
L9:
; Load from [t14] to t19
    ADDI R6, R15, 3
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R7, R5, R4
    BNE R7, R0, L8
    BEQ R0, R0, L10
L10:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 78
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t21 at FP+4
    ADDI R5, R15, 4
    LI R3, 0
    ADDI R6, R15, 4
; Store 0 to [t21]
    STORE R3, R13, R6
    BEQ R0, R0, L11
L11:
; Load from [t21] to t22
    ADDI R6, R15, 4
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R7, R5, R4
    BNE R7, R0, L12
    BEQ R0, R0, L14
L12:
; Alloca for t24 at FP+5
    ADDI R5, R15, 5
    LI R3, 0
    ADDI R6, R15, 5
; Store 0 to [t24]
    STORE R3, R13, R6
    BEQ R0, R0, L15
L15:
; Load from [t24] to t25
    ADDI R6, R15, 5
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R7, R5, R4
    BNE R7, R0, L16
    BEQ R0, R0, L18
L16:
; Load from [t21] to t27
    ADDI R6, R15, 4
    LOAD R5, R13, R6
    LI R3, 48
    ADD R7, R3, R5
    STORE R7, R0, R0
; Load from [t24] to t29
    ADDI R6, R15, 5
    LOAD R5, R13, R6
    LI R3, 48
    ADD R7, R3, R5
    STORE R7, R0, R0
    LI R3, 32
    STORE R3, R0, R0
    BEQ R0, R0, L17
L17:
; Load from [t24] to t31
    ADDI R6, R15, 5
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 5
; Store t32 to [t24]
    STORE R7, R13, R8
    BEQ R0, R0, L15
L18:
    BEQ R0, R0, L13
L13:
; Load from [t21] to t33
    ADDI R6, R15, 4
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 4
; Store t34 to [t21]
    STORE R7, R13, R8
    BEQ R0, R0, L11
L14:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 66
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t35 at FP+6
    ADDI R5, R15, 6
    LI R3, 0
    ADDI R6, R15, 6
; Store 0 to [t35]
    STORE R3, R13, R6
    BEQ R0, R0, L19
L19:
; Load from [t35] to t36
    ADDI R6, R15, 6
    LOAD R5, R13, R6
    LI R4, 5
    SLTU R7, R5, R4
    BNE R7, R0, L20
    BEQ R0, R0, L22
L20:
; Load from [t35] to t38
    ADDI R6, R15, 6
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L23
    BEQ R0, R0, L25
L23:
    BEQ R0, R0, L22
    BEQ R0, R0, L25
L25:
; Load from [t35] to t40
    ADDI R6, R15, 6
    LOAD R5, R13, R6
    LI R3, 48
    ADD R7, R3, R5
    STORE R7, R0, R0
    BEQ R0, R0, L21
L21:
; Load from [t35] to t42
    ADDI R6, R15, 6
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 6
; Store t43 to [t35]
    STORE R7, R13, R8
    BEQ R0, R0, L19
L22:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 67
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t44 at FP+7
    ADDI R5, R15, 7
    LI R3, 0
    ADDI R6, R15, 7
; Store 0 to [t44]
    STORE R3, R13, R6
    BEQ R0, R0, L26
L26:
; Load from [t44] to t45
    ADDI R6, R15, 7
    LOAD R5, R13, R6
    LI R4, 5
    SLTU R7, R5, R4
    BNE R7, R0, L27
    BEQ R0, R0, L29
L27:
; Load from [t44] to t47
    ADDI R6, R15, 7
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L30
    BEQ R0, R0, L32
L30:
    BEQ R0, R0, L28
    BEQ R0, R0, L32
L32:
; Load from [t44] to t49
    ADDI R6, R15, 7
    LOAD R5, R13, R6
    LI R3, 48
    ADD R7, R3, R5
    STORE R7, R0, R0
    BEQ R0, R0, L28
L28:
; Load from [t44] to t51
    ADDI R6, R15, 7
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 7
; Store t52 to [t44]
    STORE R7, R13, R8
    BEQ R0, R0, L26
L29:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
