; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Global variable: global_x at address 100
init_global_x:
    LI R3, 42
    LI R4, 100
    STORE R3, R0, R4
; Global variable: global_y at address 101
init_global_y:
    LI R3, 100
    LI R4, 101
    STORE R3, R0, R4
; Global variable: global_uninitialized at address 102
; Function: main
main:
; Load from @global_x to t0
    LI R9, 100
    LOAD R3, R0, R9
    STORE R3, R0, R0
    LI R4, 65
; Store 65 to @global_x
    LI R9, 100
    STORE R4, R0, R9
; Load from @global_x to t1
    LI R9, 100
    LOAD R5, R0, R9
    STORE R5, R0, R0
    LI R6, 10
; Store 10 to @global_uninitialized
    LI R9, 102
    STORE R6, R0, R9
; Load from @global_uninitialized to t2
    LI R9, 102
    LOAD R7, R0, R9
    STORE R7, R0, R0
    LI R8, 0
    ADD R3, R8, R0
    RET
