; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    ; Initialize globals
    CALL _init_globals
    CALL main
    HALT

_init_globals:
; String literal Please, ASCII art, my Ripple!\n at address 100
    LI R3, 80
    LI R4, 100
    STORE R3, R0, R4
    LI R3, 108
    LI R4, 101
    STORE R3, R0, R4
    LI R3, 101
    LI R4, 102
    STORE R3, R0, R4
    LI R3, 97
    LI R4, 103
    STORE R3, R0, R4
    LI R3, 115
    LI R4, 104
    STORE R3, R0, R4
    LI R3, 101
    LI R4, 105
    STORE R3, R0, R4
    LI R3, 44
    LI R4, 106
    STORE R3, R0, R4
    LI R3, 32
    LI R4, 107
    STORE R3, R0, R4
    LI R3, 65
    LI R4, 108
    STORE R3, R0, R4
    LI R3, 83
    LI R4, 109
    STORE R3, R0, R4
    LI R3, 67
    LI R4, 110
    STORE R3, R0, R4
    LI R3, 73
    LI R4, 111
    STORE R3, R0, R4
    LI R3, 73
    LI R4, 112
    STORE R3, R0, R4
    LI R3, 32
    LI R4, 113
    STORE R3, R0, R4
    LI R3, 97
    LI R4, 114
    STORE R3, R0, R4
    LI R3, 114
    LI R4, 115
    STORE R3, R0, R4
    LI R3, 116
    LI R4, 116
    STORE R3, R0, R4
    LI R3, 44
    LI R4, 117
    STORE R3, R0, R4
    LI R3, 32
    LI R4, 118
    STORE R3, R0, R4
    LI R3, 109
    LI R4, 119
    STORE R3, R0, R4
    LI R3, 121
    LI R4, 120
    STORE R3, R0, R4
    LI R3, 32
    LI R4, 121
    STORE R3, R0, R4
    LI R3, 82
    LI R4, 122
    STORE R3, R0, R4
    LI R3, 105
    LI R4, 123
    STORE R3, R0, R4
    LI R3, 112
    LI R4, 124
    STORE R3, R0, R4
    LI R3, 112
    LI R4, 125
    STORE R3, R0, R4
    LI R3, 108
    LI R4, 126
    STORE R3, R0, R4
    LI R3, 101
    LI R4, 127
    STORE R3, R0, R4
    LI R3, 33
    LI R4, 128
    STORE R3, R0, R4
    LI R3, 10
    LI R4, 129
    STORE R3, R0, R4
    LI R3, 0
    LI R4, 130
    STORE R3, R0, R4
    RET
; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R6, 100
    ADDI R7, R15, 1
; Store @__str_0_506c656173652c204153434949206172742c206d7920526970706c65210a to [t0]
    STORE R6, R13, R7
; Load from [t0] to t1
    ADDI R6, R15, 1
    LOAD R5, R13, R6
; GetElementPtr t2 = t1 + offsets
;   Base t1 in R5
    LI R3, 0
    ADD R7, R5, R3
; Load from [t2] to t3
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R7
    STORE R8, R0, R0
; Load from [t0] to t4
    ADDI R6, R15, 1
    LOAD R5, R13, R6
; GetElementPtr t5 = t4 + offsets
;   Base t4 in R5
    LI R3, 1
    ADD R7, R5, R3
; Load from [t5] to t6
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R7
    STORE R8, R0, R0
; Load from [t0] to t7
    ADDI R6, R15, 1
    LOAD R5, R13, R6
; GetElementPtr t8 = t7 + offsets
;   Base t7 in R5
    LI R3, 2
    ADD R7, R5, R3
; Load from [t8] to t9
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R7
    STORE R8, R0, R0
; Load from [t0] to t10
    ADDI R6, R15, 1
    LOAD R5, R13, R6
; GetElementPtr t11 = t10 + offsets
;   Base t10 in R5
    LI R3, 3
    ADD R7, R5, R3
; Load from [t11] to t12
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R7
    STORE R8, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
