; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    ; Initialize globals
    CALL _init_globals
    CALL main
    HALT

_init_globals:
; String literal: "A" at address 100
    LI R3, 65
    LI R4, 100
    STORE R3, R0, R4
    LI R3, 0
    LI R4, 101
    STORE R3, R0, R4
    RET
; Function: main
main:
; Alloca for t0
    LI R4, 100
; Store @__str_0_41 to t0
    LI R5, 65
    STORE R5, R0, R0
    LI R6, 0
    ADD R3, R6, R0
    RET
