; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    ; Initialize globals
    CALL _init_globals
    CALL main
    HALT

_init_globals:
; Global variable: global_val at address 100
    LI R3, 42
    LI R4, 100
    STORE R3, R0, R4
    RET
; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R3, 10
    ADDI R6, R15, 1
; Store 10 to [t0]
    STORE R3, R13, R6
; Alloca for t1 at FP+2
    ADDI R5, R15, 2
    ADDI R6, R15, 1
    ADDI R7, R15, 2
; Store t0 to [t1]
    STORE R6, R13, R7
; Alloca for t2 at FP+3
    ADDI R5, R15, 3
; Load from [t1] to t3
    ADDI R7, R15, 2
    LOAD R6, R13, R7
; Load from [t3] to t4
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R6
    ADDI R9, R15, 3
; Store t4 to [t2]
    STORE R8, R13, R9
; Load from [t1] to t5
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R3, 20
; Store 20 to [t5]
; WARNING: Assuming unknown pointer points to global memory
    STORE R3, R0, R5
; Load from [t0] to t6
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 20
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L1
    BEQ R0, R0, L3
L1:
    LI R3, 49
    STORE R3, R0, R0
    BEQ R0, R0, L3
L3:
; Alloca for t8 at FP+4
    ADDI R5, R15, 4
    LI R6, 100
    ADDI R7, R15, 4
; Store @global_val to [t8]
    STORE R6, R13, R7
; Load from [t8] to t9
    ADDI R6, R15, 4
    LOAD R5, R13, R6
; Load from [t9] to t10
; WARNING: Assuming unknown pointer points to global memory
    LOAD R7, R0, R5
    LI R4, 42
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L4
    BEQ R0, R0, L6
L4:
    LI R3, 50
    STORE R3, R0, R0
    BEQ R0, R0, L6
L6:
; Load from [t8] to t12
    ADDI R6, R15, 4
    LOAD R5, R13, R6
    LI R3, 100
; Store 100 to [t12]
; WARNING: Assuming unknown pointer points to global memory
    STORE R3, R0, R5
; Load from [@global_val] to t13
    LI R6, 100
    LOAD R5, R0, R6
    LI R4, 100
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L7
    BEQ R0, R0, L9
L7:
    LI R3, 51
    STORE R3, R0, R0
    BEQ R0, R0, L9
L9:
; Alloca for t15 at FP+5
    ADDI R5, R15, 5
    LI R3, 5
    ADDI R6, R15, 5
; Store 5 to [t15]
    STORE R3, R13, R6
; Alloca for t16 at FP+6
    ADDI R5, R15, 6
    ADDI R6, R15, 5
    ADDI R7, R15, 6
; Store t15 to [t16]
    STORE R6, R13, R7
; Alloca for t17 at FP+7
    ADDI R5, R15, 7
    ADDI R6, R15, 6
    ADDI R7, R15, 7
; Store t16 to [t17]
    STORE R6, R13, R7
; Load from [t17] to t18
    ADDI R6, R15, 7
    LOAD R5, R13, R6
; Load from [t18] to t19
; WARNING: Assuming unknown pointer points to global memory
    LOAD R7, R0, R5
    LI R3, 15
; Store 15 to [t19]
; WARNING: Assuming unknown pointer points to global memory
    STORE R3, R0, R7
; Load from [t15] to t20
    ADDI R6, R15, 5
    LOAD R5, R13, R6
    LI R4, 15
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L10
    BEQ R0, R0, L12
L10:
    LI R3, 52
    STORE R3, R0, R0
    BEQ R0, R0, L12
L12:
; Alloca for t22 at FP+8
    ADDI R5, R15, 8
    LI R3, 1
    ADDI R6, R15, 8
; Store 1 to [t22]
    STORE R3, R13, R6
; Alloca for t23 at FP+9
    ADDI R5, R15, 9
    LI R3, 2
    ADDI R6, R15, 9
; Store 2 to [t23]
    STORE R3, R13, R6
; Alloca for t24 at FP+10
    ADDI R5, R15, 10
    ADDI R6, R15, 8
    ADDI R7, R15, 10
; Store t22 to [t24]
    STORE R6, R13, R7
; Alloca for t25 at FP+11
    ADDI R5, R15, 11
    ADDI R6, R15, 9
    ADDI R7, R15, 11
; Store t23 to [t25]
    STORE R6, R13, R7
; Alloca for t26 at FP+12
    ADDI R5, R15, 12
; Load from [t24] to t27
    ADDI R7, R15, 10
    LOAD R6, R13, R7
; Load from [t27] to t28
; WARNING: Assuming unknown pointer points to global memory
    LOAD R8, R0, R6
    ADDI R9, R15, 12
; Store t28 to [t26]
    STORE R8, R13, R9
; Load from [t25] to t29
    ADDI R6, R15, 11
    LOAD R5, R13, R6
; Load from [t29] to t30
; WARNING: Assuming unknown pointer points to global memory
    LOAD R7, R0, R5
; Load from [t24] to t31
    ADDI R9, R15, 10
    LOAD R8, R13, R9
; Store t30 to [t31]
; WARNING: Assuming unknown pointer points to global memory
    STORE R7, R0, R8
; Load from [t26] to t32
    ADDI R6, R15, 12
    LOAD R5, R13, R6
; Load from [t25] to t33
    ADDI R8, R15, 11
    LOAD R7, R13, R8
; Store t32 to [t33]
; WARNING: Assuming unknown pointer points to global memory
    STORE R5, R0, R7
; Load from [t22] to t34
    ADDI R6, R15, 8
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L13
    BEQ R0, R0, L15
L13:
; Load from [t23] to t36
    ADDI R6, R15, 9
    LOAD R5, R13, R6
    LI R4, 1
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L16
    BEQ R0, R0, L18
L16:
    LI R3, 53
    STORE R3, R0, R0
    BEQ R0, R0, L18
L18:
    BEQ R0, R0, L15
L15:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
