; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Global variable: global_x
; Global variable: global_y
; Global variable: global_uninitialized
; Function: main
main:
; Load from @global_x to t0 (uninitialized)
    LI R3, 0
    STORE R3, R0, R0
    LI R4, 65
; Store 65 to @global_x
; Load stored_at_@global_x from @global_x to t1
    ADD R5, R4, R0
    STORE R5, R0, R0
    LI R6, 10
; Store 10 to @global_uninitialized
; Load stored_at_@global_uninitialized from @global_uninitialized to t2
    ADD R7, R6, R0
    STORE R7, R0, R0
    LI R8, 0
    ADD R3, R8, R0
    RET
