; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R3, 10
    ADDI R6, R15, 1
; Store 10 to [t0]
    STORE R3, R13, R6
    ADDI R5, R15, 1
    LI R4, 1
    ADD R6, R5, R4
    LI R3, 20
; Store 20 to [t1]
; WARNING: Assuming unknown pointer points to global memory
    STORE R3, R0, R6
; Load from [t0] to t2
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 10
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L1
    BEQ R0, R0, L2
L1:
    LI R3, 49
    STORE R3, R0, R0
    BEQ R0, R0, L3
L2:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L3
L3:
    ADDI R5, R15, 1
    LI R4, 1
    ADD R6, R5, R4
; Load from [t4] to t5
; WARNING: Assuming unknown pointer points to global memory
    LOAD R7, R0, R6
    LI R4, 20
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L4
    BEQ R0, R0, L5
L4:
    LI R3, 50
    STORE R3, R0, R0
    BEQ R0, R0, L6
L5:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L6
L6:
    LI R3, 30
    ADDI R5, R15, 1
; Store 30 to [t0]
    STORE R3, R13, R5
; Load from [t0] to t7
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 30
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L7
    BEQ R0, R0, L8
L7:
    LI R3, 51
    STORE R3, R0, R0
    BEQ R0, R0, L9
L8:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L9
L9:
    ADDI R5, R15, 1
    LI R4, 1
    ADD R6, R5, R4
    LI R3, 40
; Store 40 to [t9]
; WARNING: Assuming unknown pointer points to global memory
    STORE R3, R0, R6
    ADDI R5, R15, 1
    LI R4, 1
    ADD R6, R5, R4
; Load from [t10] to t11
; WARNING: Assuming unknown pointer points to global memory
    LOAD R7, R0, R6
    LI R4, 40
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L10
    BEQ R0, R0, L11
L10:
    LI R3, 52
    STORE R3, R0, R0
    BEQ R0, R0, L12
L11:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L12
L12:
    LI R3, 50
    ADDI R5, R15, 1
; Store 50 to [t0]
    STORE R3, R13, R5
; Load from [t0] to t13
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 50
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    ADDI R9, R15, 1
    LI R4, 1
    ADD R8, R9, R4
; Load from [t15] to t16
; WARNING: Assuming unknown pointer points to global memory
    LOAD R10, R0, R8
    LI R4, 40
; Spilling addr_t0_30 to FP+0
    ADDI R12, R15, 0
    STORE R6, R13, R12
; Spilling eq_temp1_34 to FP+1
    ADDI R12, R15, 1
    STORE R6, R13, R12
    SLTU R6, R10, R4
    SLTU R6, R4, R10
    OR R11, R6, R6
    LI R6, 1
    SUB R11, R6, R11
    ADD R6, R7, R11
    BNE R6, R0, L13
    BEQ R0, R0, L14
L13:
    LI R3, 53
    STORE R3, R0, R0
    BEQ R0, R0, L15
L14:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L15
L15:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
