; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    LI R3, 49
    STORE R3, R0, R0
    LI R4, 58
    STORE R4, R0, R0
    LI R5, 5
    LI R6, 3
    SLTU R7, R6, R5
    BNE R7, R0, L1
    BEQ R0, R0, L2
L1:
    LI R8, 84
    STORE R8, R0, R0
    BEQ R0, R0, L3
L2:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L3
L3:
    LI R4, 10
    STORE R4, R0, R0
    LI R5, 50
    STORE R5, R0, R0
    LI R6, 58
    STORE R6, R0, R0
    LI R7, 2
    LI R8, 5
    SLTU R3, R8, R7
    BNE R3, R0, L4
    BEQ R0, R0, L5
L4:
    LI R4, 84
    STORE R4, R0, R0
    BEQ R0, R0, L6
L5:
    LI R5, 70
    STORE R5, R0, R0
    BEQ R0, R0, L6
L6:
    LI R6, 10
    STORE R6, R0, R0
    LI R7, 51
    STORE R7, R0, R0
    LI R8, 58
    STORE R8, R0, R0
    LI R3, 7
    LI R4, 7
    SLTU R9, R3, R4
    SLTU R10, R4, R3
    OR R5, R9, R10
    LI R9, 1
    SUB R5, R9, R5
    BNE R5, R0, L7
    BEQ R0, R0, L8
L7:
    LI R6, 84
    STORE R6, R0, R0
    BEQ R0, R0, L9
L8:
    LI R7, 70
    STORE R7, R0, R0
    BEQ R0, R0, L9
L9:
    LI R8, 10
    STORE R8, R0, R0
    LI R3, 52
    STORE R3, R0, R0
    LI R4, 58
    STORE R4, R0, R0
    LI R5, 3
    LI R6, 3
    SLTU R9, R5, R6
    SLTU R10, R6, R5
    OR R7, R9, R10
    BNE R7, R0, L10
    BEQ R0, R0, L11
L10:
    LI R8, 84
    STORE R8, R0, R0
    BEQ R0, R0, L12
L11:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L12
L12:
    LI R4, 10
    STORE R4, R0, R0
    LI R5, 53
    STORE R5, R0, R0
    LI R6, 58
    STORE R6, R0, R0
    LI R7, 10
    LI R8, 5
    SLTU R3, R8, R7
    BNE R3, R0, L13
    BEQ R0, R0, L14
L13:
    LI R4, 3
    LI R5, 7
    SLTU R6, R4, R5
    BNE R6, R0, L16
    BEQ R0, R0, L17
L16:
    LI R7, 65
    STORE R7, R0, R0
    BEQ R0, R0, L18
L17:
    LI R8, 66
    STORE R8, R0, R0
    BEQ R0, R0, L18
L18:
    BEQ R0, R0, L15
L14:
    LI R3, 67
    STORE R3, R0, R0
    BEQ R0, R0, L15
L15:
    LI R4, 10
    STORE R4, R0, R0
    LI R5, 54
    STORE R5, R0, R0
    LI R6, 58
    STORE R6, R0, R0
; Alloca for t6 at FP+1
    ADDI R7, R15, 1
    LI R8, 2
    ADDI R3, R15, 1
; Store 2 to [t6]
    STORE R8, R13, R3
    ADDI R5, R15, 1
; Load from [t6] to t7
    LOAD R4, R13, R5
    LI R6, 1
    SLTU R9, R4, R6
    SLTU R10, R6, R4
    OR R7, R9, R10
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L19
    BEQ R0, R0, L20
L19:
    LI R8, 49
    STORE R8, R0, R0
    BEQ R0, R0, L21
L20:
    ADDI R4, R15, 1
; Load from [t6] to t9
    LOAD R3, R13, R4
    LI R5, 2
    SLTU R9, R3, R5
    SLTU R10, R5, R3
    OR R6, R9, R10
    LI R9, 1
    SUB R6, R9, R6
    BNE R6, R0, L22
    BEQ R0, R0, L23
L22:
    LI R7, 50
    STORE R7, R0, R0
    BEQ R0, R0, L24
L23:
    ADDI R3, R15, 1
; Load from [t6] to t11
    LOAD R8, R13, R3
    LI R4, 3
    SLTU R9, R8, R4
    SLTU R10, R4, R8
    OR R5, R9, R10
    LI R9, 1
    SUB R5, R9, R5
    BNE R5, R0, L25
    BEQ R0, R0, L26
L25:
    LI R6, 51
    STORE R6, R0, R0
    BEQ R0, R0, L27
L26:
    LI R7, 88
    STORE R7, R0, R0
    BEQ R0, R0, L27
L27:
    BEQ R0, R0, L24
L24:
    BEQ R0, R0, L21
L21:
    LI R8, 10
    STORE R8, R0, R0
    LI R3, 55
    STORE R3, R0, R0
    LI R4, 58
    STORE R4, R0, R0
    LI R5, 1
    LI R6, 2
    SLTU R7, R5, R6
    BNE R7, R0, L28
    BEQ R0, R0, L29
L28:
    LI R8, 79
    STORE R8, R0, R0
    LI R3, 75
    STORE R3, R0, R0
    BEQ R0, R0, L30
L29:
    LI R4, 78
    STORE R4, R0, R0
    LI R5, 79
    STORE R5, R0, R0
    BEQ R0, R0, L30
L30:
    LI R6, 10
    STORE R6, R0, R0
    LI R7, 56
    STORE R7, R0, R0
    LI R8, 58
    STORE R8, R0, R0
    LI R3, 3
    LI R4, 2
    SLTU R5, R4, R3
    BNE R5, R0, L31
    BEQ R0, R0, L33
L31:
    LI R6, 89
    STORE R6, R0, R0
    BEQ R0, R0, L33
L33:
    LI R7, 10
    STORE R7, R0, R0
    LI R8, 57
    STORE R8, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t15 at FP+2
    ADDI R4, R15, 2
    LI R5, 5
    ADDI R6, R15, 2
; Store 5 to [t15]
    STORE R5, R13, R6
; Alloca for t16 at FP+3
    ADDI R7, R15, 3
    LI R8, 3
    ADDI R3, R15, 3
; Store 3 to [t16]
    STORE R8, R13, R3
    ADDI R5, R15, 2
; Load from [t15] to t17
    LOAD R4, R13, R5
    ADDI R7, R15, 3
; Load from [t16] to t18
    LOAD R6, R13, R7
    SLTU R8, R6, R4
    BNE R8, R0, L34
    BEQ R0, R0, L35
L34:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L36
L35:
    LI R4, 70
    STORE R4, R0, R0
    BEQ R0, R0, L36
L36:
    LI R5, 10
    STORE R5, R0, R0
    LI R6, 65
    STORE R6, R0, R0
    LI R7, 58
    STORE R7, R0, R0
    LI R8, 5
    BNE R8, R0, L37
    BEQ R0, R0, L38
L37:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L39
L38:
    LI R4, 70
    STORE R4, R0, R0
    BEQ R0, R0, L39
L39:
    LI R5, 10
    STORE R5, R0, R0
    LI R6, 66
    STORE R6, R0, R0
    LI R7, 58
    STORE R7, R0, R0
    LI R8, 0
    BNE R8, R0, L40
    BEQ R0, R0, L41
L40:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L42
L41:
    LI R4, 70
    STORE R4, R0, R0
    BEQ R0, R0, L42
L42:
    LI R5, 10
    STORE R5, R0, R0
    LI R6, 0
    ADD R3, R6, R0
    RET
