; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
; GetElementPtr t1 = t0 + offsets
    ADDI R6, R15, 1
;   Base t0 in R6
    LI R3, 0
    ADD R7, R6, R3
    LI R4, 2
; Store 2 to [t1]
    STORE R4, R13, R7
; GetElementPtr t2 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 1
    ADD R6, R5, R3
    LI R4, 3
; Store 3 to [t2]
    STORE R4, R13, R6
; GetElementPtr t3 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 2
    ADD R6, R5, R3
    LI R4, 5
; Store 5 to [t3]
    STORE R4, R13, R6
; GetElementPtr t4 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 3
    ADD R6, R5, R3
    LI R4, 7
; Store 7 to [t4]
    STORE R4, R13, R6
; GetElementPtr t5 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 4
    ADD R6, R5, R3
    LI R4, 11
; Store 11 to [t5]
    STORE R4, R13, R6
; Alloca for t6 at FP+6
    ADDI R5, R15, 6
; GetElementPtr t7 = t6 + offsets
    ADDI R6, R15, 6
;   Base t6 in R6
    LI R3, 0
    ADD R7, R6, R3
    LI R4, 97
; Store 97 to [t7]
    STORE R4, R13, R7
; GetElementPtr t8 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 1
    ADD R6, R5, R3
    LI R4, 101
; Store 101 to [t8]
    STORE R4, R13, R6
; GetElementPtr t9 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 2
    ADD R6, R5, R3
    LI R4, 105
; Store 105 to [t9]
    STORE R4, R13, R6
; GetElementPtr t10 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 3
    ADD R6, R5, R3
    LI R4, 111
; Store 111 to [t10]
    STORE R4, R13, R6
; GetElementPtr t11 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 4
    ADD R6, R5, R3
    LI R4, 117
; Store 117 to [t11]
    STORE R4, R13, R6
; GetElementPtr t12 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 5
    ADD R6, R5, R3
    LI R4, 0
; Store 0 to [t12]
    STORE R4, R13, R6
; Alloca for t13 at FP+12
    ADDI R5, R15, 12
; GetElementPtr t14 = t13 + offsets
    ADDI R6, R15, 12
;   Base t13 in R6
    LI R3, 0
    ADD R7, R6, R3
    LI R4, 72
; Store 72 to [t14]
    STORE R4, R13, R7
; GetElementPtr t15 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 1
    ADD R6, R5, R3
    LI R4, 101
; Store 101 to [t15]
    STORE R4, R13, R6
; GetElementPtr t16 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 2
    ADD R6, R5, R3
    LI R4, 108
; Store 108 to [t16]
    STORE R4, R13, R6
; GetElementPtr t17 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 3
    ADD R6, R5, R3
    LI R4, 108
; Store 108 to [t17]
    STORE R4, R13, R6
; GetElementPtr t18 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 4
    ADD R6, R5, R3
    LI R4, 111
; Store 111 to [t18]
    STORE R4, R13, R6
; GetElementPtr t19 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 5
    ADD R6, R5, R3
    LI R4, 0
; Store 0 to [t19]
    STORE R4, R13, R6
; GetElementPtr t20 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 0
    ADD R6, R5, R3
; Load from [t20] to t21
    LOAD R7, R13, R6
    LI R4, 2
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L1
    BEQ R0, R0, L2
L1:
    LI R3, 49
    STORE R3, R0, R0
    BEQ R0, R0, L3
L2:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L3
L3:
; GetElementPtr t23 = t0 + offsets
    ADDI R5, R15, 1
;   Base t0 in R5
    LI R3, 2
    ADD R6, R5, R3
; Load from [t23] to t24
    LOAD R7, R13, R6
    LI R4, 5
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L4
    BEQ R0, R0, L5
L4:
    LI R3, 50
    STORE R3, R0, R0
    BEQ R0, R0, L6
L5:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L6
L6:
; GetElementPtr t26 = t6 + offsets
    ADDI R5, R15, 6
;   Base t6 in R5
    LI R3, 0
    ADD R6, R5, R3
; Load from [t26] to t27
    LOAD R7, R13, R6
    LI R4, 97
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L7
    BEQ R0, R0, L8
L7:
    LI R3, 51
    STORE R3, R0, R0
    BEQ R0, R0, L9
L8:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L9
L9:
; GetElementPtr t29 = t13 + offsets
    ADDI R5, R15, 12
;   Base t13 in R5
    LI R3, 1
    ADD R6, R5, R3
; Load from [t29] to t30
    LOAD R7, R13, R6
    LI R4, 101
    SLTU R9, R7, R4
    SLTU R10, R4, R7
    OR R8, R9, R10
    LI R10, 1
    SUB R8, R10, R8
    BNE R8, R0, L10
    BEQ R0, R0, L11
L10:
    LI R3, 52
    STORE R3, R0, R0
    BEQ R0, R0, L12
L11:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L12
L12:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
