; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
; Alloca for t0 at FP+1
    ADDI R5, R15, 1
    LI R3, 0
    ADDI R6, R15, 1
; Store 0 to [t0]
    STORE R3, R13, R6
; Alloca for t1 at FP+2
    ADDI R5, R15, 2
    LI R3, 0
    ADDI R6, R15, 2
; Store 0 to [t1]
    STORE R3, R13, R6
    BEQ R0, R0, L1
L1:
; Load from [t0] to t2
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R7, R5, R4
    BNE R7, R0, L2
    BEQ R0, R0, L3
L2:
; Load from [t1] to t4
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 2
; Store t5 to [t1]
    STORE R7, R13, R8
; Load from [t0] to t6
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 1
    ADD R7, R5, R4
    ADDI R8, R15, 1
; Store t7 to [t0]
    STORE R7, R13, R8
    BEQ R0, R0, L1
L3:
; Load from [t1] to t8
    ADDI R6, R15, 2
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L4
    BEQ R0, R0, L5
L4:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L6
L5:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L6
L6:
; Load from [t0] to t10
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L7
    BEQ R0, R0, L8
L7:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L9
L8:
    LI R3, 78
    STORE R3, R0, R0
    BEQ R0, R0, L9
L9:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
