; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
    LI R3, 49
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 5
    LI R4, 3
    SLTU R5, R4, R3
    BNE R5, R0, L1
    BEQ R0, R0, L2
L1:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L3
L2:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L3
L3:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 50
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 2
    LI R4, 5
    SLTU R5, R4, R3
    BNE R5, R0, L4
    BEQ R0, R0, L5
L4:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L6
L5:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L6
L6:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 51
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 7
    LI R4, 7
    SLTU R6, R3, R4
    SLTU R7, R4, R3
    OR R5, R6, R7
    LI R7, 1
    SUB R5, R7, R5
    BNE R5, R0, L7
    BEQ R0, R0, L8
L7:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L9
L8:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L9
L9:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 52
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 3
    LI R4, 3
    SLTU R6, R3, R4
    SLTU R7, R4, R3
    OR R5, R6, R7
    BNE R5, R0, L10
    BEQ R0, R0, L11
L10:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L12
L11:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L12
L12:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 53
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 10
    LI R4, 5
    SLTU R5, R4, R3
    BNE R5, R0, L13
    BEQ R0, R0, L14
L13:
    LI R3, 3
    LI R4, 7
    SLTU R5, R3, R4
    BNE R5, R0, L16
    BEQ R0, R0, L17
L16:
    LI R3, 65
    STORE R3, R0, R0
    BEQ R0, R0, L18
L17:
    LI R3, 66
    STORE R3, R0, R0
    BEQ R0, R0, L18
L18:
    BEQ R0, R0, L15
L14:
    LI R3, 67
    STORE R3, R0, R0
    BEQ R0, R0, L15
L15:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 54
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t6 at FP+1
    ADDI R5, R15, 1
    LI R3, 2
    ADDI R6, R15, 1
; Store 2 to [t6]
    STORE R3, R13, R6
; Load from [t6] to t7
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 1
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L19
    BEQ R0, R0, L20
L19:
    LI R3, 49
    STORE R3, R0, R0
    BEQ R0, R0, L21
L20:
; Load from [t6] to t9
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L22
    BEQ R0, R0, L23
L22:
    LI R3, 50
    STORE R3, R0, R0
    BEQ R0, R0, L24
L23:
; Load from [t6] to t11
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, L25
    BEQ R0, R0, L26
L25:
    LI R3, 51
    STORE R3, R0, R0
    BEQ R0, R0, L27
L26:
    LI R3, 88
    STORE R3, R0, R0
    BEQ R0, R0, L27
L27:
    BEQ R0, R0, L24
L24:
    BEQ R0, R0, L21
L21:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 55
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 1
    LI R4, 2
    SLTU R5, R3, R4
    BNE R5, R0, L28
    BEQ R0, R0, L29
L28:
    LI R3, 79
    STORE R3, R0, R0
    LI R3, 75
    STORE R3, R0, R0
    BEQ R0, R0, L30
L29:
    LI R3, 78
    STORE R3, R0, R0
    LI R3, 79
    STORE R3, R0, R0
    BEQ R0, R0, L30
L30:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 56
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 3
    LI R4, 2
    SLTU R5, R4, R3
    BNE R5, R0, L31
    BEQ R0, R0, L33
L31:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, L33
L33:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 57
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t15 at FP+2
    ADDI R5, R15, 2
    LI R3, 5
    ADDI R6, R15, 2
; Store 5 to [t15]
    STORE R3, R13, R6
; Alloca for t16 at FP+3
    ADDI R5, R15, 3
    LI R3, 3
    ADDI R6, R15, 3
; Store 3 to [t16]
    STORE R3, R13, R6
; Load from [t15] to t17
    ADDI R6, R15, 2
    LOAD R5, R13, R6
; Load from [t16] to t18
    ADDI R8, R15, 3
    LOAD R7, R13, R8
    SLTU R9, R7, R5
    BNE R9, R0, L34
    BEQ R0, R0, L35
L34:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L36
L35:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L36
L36:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 65
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 5
    BNE R3, R0, L37
    BEQ R0, R0, L38
L37:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L39
L38:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L39
L39:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 66
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 0
    BNE R3, R0, L40
    BEQ R0, R0, L41
L40:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, L42
L41:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, L42
L42:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
