; Generated by Ripple C99 Compiler (rcc)

; Program entry point
_start:
    ; Initialize stack pointer
    LI R13, 0       ; Stack bank = 0
    LI R14, 1000   ; Stack pointer starts at 1000
    LI R15, 1000   ; Frame pointer starts at 1000
    CALL main
    HALT

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
    LI R3, 72
    STORE R3, R0, R0
    LI R3, 101
    STORE R3, R0, R0
    LI R3, 108
    STORE R3, R0, R0
    LI R3, 108
    STORE R3, R0, R0
    LI R3, 111
    STORE R3, R0, R0
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
