; Generated by Ripple C99 Compiler (rcc)

; Function: main
main:
    STORE RA, R13, R14
    ADDI R14, R14, 1
    STORE R15, R13, R14
    ADDI R14, R14, 1
    ADD R15, R14, R0
    LI R3, 49
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 5
    LI R4, 3
    SLTU R5, R4, R3
    BNE R5, R0, main_L1
    BEQ R0, R0, main_L2
main_L1:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L3
main_L2:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L3
main_L3:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 50
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 2
    LI R4, 5
    SLTU R5, R4, R3
    BNE R5, R0, main_L4
    BEQ R0, R0, main_L5
main_L4:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L6
main_L5:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L6
main_L6:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 51
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 7
    LI R4, 7
    SLTU R6, R3, R4
    SLTU R7, R4, R3
    OR R5, R6, R7
    LI R7, 1
    SUB R5, R7, R5
    BNE R5, R0, main_L7
    BEQ R0, R0, main_L8
main_L7:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L9
main_L8:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L9
main_L9:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 52
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 3
    LI R4, 3
    SLTU R6, R3, R4
    SLTU R7, R4, R3
    OR R5, R6, R7
    BNE R5, R0, main_L10
    BEQ R0, R0, main_L11
main_L10:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L12
main_L11:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L12
main_L12:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 53
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 10
    LI R4, 5
    SLTU R5, R4, R3
    BNE R5, R0, main_L13
    BEQ R0, R0, main_L14
main_L13:
    LI R3, 3
    LI R4, 7
    SLTU R5, R3, R4
    BNE R5, R0, main_L16
    BEQ R0, R0, main_L17
main_L16:
    LI R3, 65
    STORE R3, R0, R0
    BEQ R0, R0, main_L18
main_L17:
    LI R3, 66
    STORE R3, R0, R0
    BEQ R0, R0, main_L18
main_L18:
    BEQ R0, R0, main_L15
main_L14:
    LI R3, 67
    STORE R3, R0, R0
    BEQ R0, R0, main_L15
main_L15:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 54
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t6 at FP+1
    ADDI R5, R15, 1
    LI R3, 2
    ADDI R6, R15, 1
; Store 2 to [t6]
    STORE R3, R13, R6
; Load from [t6] to t7
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 1
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, main_L19
    BEQ R0, R0, main_L20
main_L19:
    LI R3, 49
    STORE R3, R0, R0
    BEQ R0, R0, main_L21
main_L20:
; Load from [t6] to t9
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 2
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, main_L22
    BEQ R0, R0, main_L23
main_L22:
    LI R3, 50
    STORE R3, R0, R0
    BEQ R0, R0, main_L24
main_L23:
; Load from [t6] to t11
    ADDI R6, R15, 1
    LOAD R5, R13, R6
    LI R4, 3
    SLTU R8, R5, R4
    SLTU R9, R4, R5
    OR R7, R8, R9
    LI R9, 1
    SUB R7, R9, R7
    BNE R7, R0, main_L25
    BEQ R0, R0, main_L26
main_L25:
    LI R3, 51
    STORE R3, R0, R0
    BEQ R0, R0, main_L27
main_L26:
    LI R3, 88
    STORE R3, R0, R0
    BEQ R0, R0, main_L27
main_L27:
    BEQ R0, R0, main_L24
main_L24:
    BEQ R0, R0, main_L21
main_L21:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 55
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 1
    LI R4, 2
    SLTU R5, R3, R4
    BNE R5, R0, main_L28
    BEQ R0, R0, main_L29
main_L28:
    LI R3, 79
    STORE R3, R0, R0
    LI R3, 75
    STORE R3, R0, R0
    BEQ R0, R0, main_L30
main_L29:
    LI R3, 78
    STORE R3, R0, R0
    LI R3, 79
    STORE R3, R0, R0
    BEQ R0, R0, main_L30
main_L30:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 56
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 3
    LI R4, 2
    SLTU R5, R4, R3
    BNE R5, R0, main_L31
    BEQ R0, R0, main_L33
main_L31:
    LI R3, 89
    STORE R3, R0, R0
    BEQ R0, R0, main_L33
main_L33:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 57
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
; Alloca for t15 at FP+2
    ADDI R5, R15, 2
    LI R3, 5
    ADDI R6, R15, 2
; Store 5 to [t15]
    STORE R3, R13, R6
; Alloca for t16 at FP+3
    ADDI R5, R15, 3
    LI R3, 3
    ADDI R6, R15, 3
; Store 3 to [t16]
    STORE R3, R13, R6
; Load from [t15] to t17
    ADDI R6, R15, 2
    LOAD R5, R13, R6
; Load from [t16] to t18
    ADDI R8, R15, 3
    LOAD R7, R13, R8
    SLTU R9, R7, R5
    BNE R9, R0, main_L34
    BEQ R0, R0, main_L35
main_L34:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L36
main_L35:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L36
main_L36:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 65
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 5
    BNE R3, R0, main_L37
    BEQ R0, R0, main_L38
main_L37:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L39
main_L38:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L39
main_L39:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 66
    STORE R3, R0, R0
    LI R3, 58
    STORE R3, R0, R0
    LI R3, 0
    BNE R3, R0, main_L40
    BEQ R0, R0, main_L41
main_L40:
    LI R3, 84
    STORE R3, R0, R0
    BEQ R0, R0, main_L42
main_L41:
    LI R3, 70
    STORE R3, R0, R0
    BEQ R0, R0, main_L42
main_L42:
    LI R3, 10
    STORE R3, R0, R0
    LI R3, 0
    ADD R14, R15, R0
    ADDI R14, R14, -1
    LOAD R15, R13, R14
    ADDI R14, R14, -1
    LOAD RA, R13, R14
    RET
